# -*- coding: utf-8 -*-
"""knn_species_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l3OgmSRNP2Nkoe4JHyofJrG-U7aK_dOo
"""

import os
import time
import json
import tarfile

import numpy as np
import pandas as pd

import cv2
from skimage.feature import hog, local_binary_pattern
from joblib import Parallel, delayed

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import (
    accuracy_score, balanced_accuracy_score, top_k_accuracy_score,
    precision_recall_fscore_support, confusion_matrix, classification_report,
)
import matplotlib
import matplotlib.pyplot as plt

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
class CONFIG:
    """Central configuration for paths, feature extraction and the classifier."""

    # Directory at which Google Drive is mounted.
    MOUNT_POINT = "/content/gdrive"
    # Dataset location: label CSVs and the two source archives.
    DRIVE_ROOT = "/content/gdrive/MyDrive/CV_Proj_Dataset"
    # Destination for cached features, metrics and figures.
    RESULTS_ROOT = "/content/gdrive/MyDrive/COMP9517 GROUP PROJECT"
    # Local working directory holding the extracted JPEGs.
    WORK_DIR = "/content/work"

    # train/val images reside in train_mini.tar.gz; test images in val.tar.gz.
    TRAIN_TAR = "train_mini.tar.gz"
    VAL_TAR = "val.tar.gz"

    TRAIN_CSV = "train_label_500_species.csv"
    VAL_CSV = "val_label_500_species.csv"
    TEST_CSV = "test_label_500_species.csv"
    IMG_PATH_COL = "file_name"
    LABEL_COL = "category_id"

    # Feature extraction.
    IMG_SIZE = 128              # images are resized to IMG_SIZE x IMG_SIZE
    HSV_BINS = (8, 8, 8)        # colour histogram bins per HSV channel
    COLOR_GRID = 2              # image split into COLOR_GRID x COLOR_GRID cells
    HOG_PPC = (16, 16)          # HOG pixels per cell
    HOG_CPB = (2, 2)            # HOG cells per block
    HOG_ORIENT = 9              # HOG gradient orientation bins
    LBP_P = 24                  # LBP neighbourhood size
    LBP_R = 3                   # LBP radius
    LBP_BINS = LBP_P + 2        # bins in the uniform LBP histogram

    # Relative contribution of each descriptor block to the distance metric.
    W_COLOR = 1.0
    W_HOG = 1.0
    W_LBP = 1.0
    FEATURE_VER = "v2"          # identifier used to key the feature cache

    # Dimensionality reduction and classifier search space.
    PCA_DIMS = 300
    K_GRID = [1, 3, 5, 7, 9, 15, 21, 31, 41, 51]
    WEIGHTS_GRID = ["uniform", "distance"]
    METRIC_GRID = ["euclidean", "cosine"]

    N_JOBS = -1
    RANDOM_SEED = 42

    CACHE_DIR = os.path.join(RESULTS_ROOT, "knn_cache")
    OUT_DIR = os.path.join(RESULTS_ROOT, "knn_outputs")

# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------
def mount_drive():
    """Mount Google Drive when executing inside a Colab runtime.

    The mount is skipped when the mount point is already populated, so that the
    script can be re-run within a session without attempting to mount over an
    active mount.
    """
    try:
        from google.colab import drive
    except ImportError:
        return
    if not os.path.isdir(os.path.join(CONFIG.MOUNT_POINT, "MyDrive")):
        drive.mount(CONFIG.MOUNT_POINT)


def _basename(path):
    """Reduce a dataset-relative path to its filename."""
    return os.path.basename(str(path).strip())


def load_split(csv_name):
    """Read a label CSV and return its image filenames and class labels."""
    df = pd.read_csv(os.path.join(CONFIG.DRIVE_ROOT, csv_name))
    columns = {c.lower(): c for c in df.columns}

    img_col = CONFIG.IMG_PATH_COL if CONFIG.IMG_PATH_COL in df.columns else next(
        (columns[c] for c in ("file_name", "filename", "image", "path", "img")
         if c in columns), None)
    label_col = CONFIG.LABEL_COL if CONFIG.LABEL_COL in df.columns else next(
        (columns[c] for c in ("category_id", "label", "class_id", "species")
         if c in columns), None)
    if img_col is None or label_col is None:
        raise ValueError(f"Could not identify image/label columns in {csv_name}.")

    split = pd.DataFrame({
        "img_full": df[img_col].astype(str),
        "img": df[img_col].map(_basename),
        "label": df[label_col],
    })
    print(f"{csv_name}: {len(split)} images, {split['label'].nunique()} classes")
    return split

# ---------------------------------------------------------------------------
# Image extraction
# ---------------------------------------------------------------------------
def _extract_from_archive(tar_path, wanted):
    """Stream a tar archive once, extracting only the requested filenames."""
    if not wanted:
        return
    if not os.path.exists(tar_path):
        print(f"Archive unavailable: {tar_path} ({len(wanted)} images skipped)")
        return

    extracted = 0
    started = time.time()
    with tarfile.open(tar_path, "r:gz") as archive:
        for member in archive:
            if not member.isfile():
                continue
            name = os.path.basename(member.name)
            if name in wanted:
                source = archive.extractfile(member)
                if source is None:
                    continue
                with open(os.path.join(CONFIG.WORK_DIR, name), "wb") as target:
                    target.write(source.read())
                extracted += 1
                wanted.discard(name)
                if extracted % 2000 == 0:
                    print(f"  {extracted} images ({time.time() - started:.0f}s)")
                if not wanted:
                    break
    print(f"{os.path.basename(tar_path)}: extracted {extracted} images "
          f"in {time.time() - started:.0f}s")


def extract_needed_images(splits):
    """Extract only the images referenced by the 500-class subset.

    Images are routed to the correct archive using their dataset-relative path
    prefix, and images already present on disk are skipped so that repeated
    runs do not rescan the archives.
    """
    present = set(os.listdir(CONFIG.WORK_DIR))
    wanted = {CONFIG.TRAIN_TAR: set(), CONFIG.VAL_TAR: set()}

    for split in splits:
        for full_path, name in zip(split["img_full"], split["img"]):
            if name in present:
                continue
            prefix = str(full_path).split("/", 1)[0]
            archive = CONFIG.VAL_TAR if prefix == "val" else CONFIG.TRAIN_TAR
            wanted[archive].add(name)

    if not any(wanted.values()):
        print("All required images are already available.")
        return

    total = sum(len(names) for names in wanted.values())
    print(f"Extracting {total} images from the source archives")
    for archive, names in wanted.items():
        _extract_from_archive(os.path.join(CONFIG.DRIVE_ROOT, archive), names)

# ---------------------------------------------------------------------------
# Feature extraction
# ---------------------------------------------------------------------------
def _l2_normalise(vector):
    """Scale a vector to unit L2 norm."""
    vector = np.asarray(vector, dtype="float32")
    return vector / (np.linalg.norm(vector) + 1e-7)


def extract_features(image_path):
    """Compute the combined colour, gradient and texture descriptor.

    The three descriptor blocks are normalised independently before being
    concatenated so that a high-dimensional block (HOG) cannot dominate the
    distance computation simply by virtue of its length.
    """
    image = cv2.imread(image_path)
    if image is None:
        return None

    image = cv2.resize(image, (CONFIG.IMG_SIZE, CONFIG.IMG_SIZE))
    hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
    grey = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # Spatial colour: one HSV histogram per grid cell preserves coarse layout.
    cell_size = CONFIG.IMG_SIZE // CONFIG.COLOR_GRID
    cell_histograms = []
    for row in range(CONFIG.COLOR_GRID):
        for col in range(CONFIG.COLOR_GRID):
            cell = hsv[row * cell_size:(row + 1) * cell_size,
                       col * cell_size:(col + 1) * cell_size]
            histogram = cv2.calcHist([cell], [0, 1, 2], None, CONFIG.HSV_BINS,
                                     [0, 180, 0, 256, 0, 256]).flatten()
            cell_histograms.append(_l2_normalise(histogram))
    colour = _l2_normalise(np.concatenate(cell_histograms))

    # Gradient structure.
    gradients = _l2_normalise(hog(
        grey, orientations=CONFIG.HOG_ORIENT, pixels_per_cell=CONFIG.HOG_PPC,
        cells_per_block=CONFIG.HOG_CPB, block_norm="L2-Hys", feature_vector=True))

    # Micro-texture.
    lbp = local_binary_pattern(grey, CONFIG.LBP_P, CONFIG.LBP_R, method="uniform")
    texture, _ = np.histogram(lbp.ravel(),
                              bins=np.arange(0, CONFIG.LBP_BINS + 1),
                              range=(0, CONFIG.LBP_BINS))
    texture = _l2_normalise(texture)

    return np.concatenate([
        CONFIG.W_COLOR * colour,
        CONFIG.W_HOG * gradients,
        CONFIG.W_LBP * texture,
    ]).astype("float32")


def build_feature_matrix(split, split_name):
    """Build, cache and return the feature matrix and labels for one split."""
    cache_x = os.path.join(CONFIG.CACHE_DIR, f"X_{split_name}_{CONFIG.FEATURE_VER}.npy")
    cache_y = os.path.join(CONFIG.CACHE_DIR, f"y_{split_name}_{CONFIG.FEATURE_VER}.npy")
    if os.path.exists(cache_x) and os.path.exists(cache_y):
        print(f"{split_name}: loaded cached features")
        return np.load(cache_x), np.load(cache_y)

    paths = [os.path.join(CONFIG.WORK_DIR, name) for name in split["img"]]
    labels = split["label"].to_numpy()

    print(f"{split_name}: extracting features for {len(paths)} images")
    started = time.time()
    features = Parallel(n_jobs=CONFIG.N_JOBS)(
        delayed(extract_features)(path) for path in paths)

    usable = [i for i, feature in enumerate(features) if feature is not None]
    if not usable:
        raise RuntimeError(
            f"No readable images for the '{split_name}' split; the source "
            f"archive for this split is missing or empty.")

    X = np.vstack([features[i] for i in usable])
    y = labels[usable]
    print(f"{split_name}: {X.shape[0]} samples, {X.shape[1]} dimensions "
          f"({time.time() - started:.0f}s)")

    np.save(cache_x, X)
    np.save(cache_y, y)
    return X, y

# ---------------------------------------------------------------------------
# Model selection
# ---------------------------------------------------------------------------
def tune_knn(X_train, y_train, X_val, y_val):
    """Grid-search neighbourhood size, distance metric and weighting.

    Selection is performed exclusively on the validation split so that the test
    split remains unseen until final evaluation.
    """
    results = []
    best = {"accuracy": -1.0}

    for metric in CONFIG.METRIC_GRID:
        for weights in CONFIG.WEIGHTS_GRID:
            for k in CONFIG.K_GRID:
                model = KNeighborsClassifier(n_neighbors=k, weights=weights,
                                             metric=metric, n_jobs=CONFIG.N_JOBS)
                model.fit(X_train, y_train)
                accuracy = accuracy_score(y_val, model.predict(X_val))
                results.append((metric, weights, k, accuracy))
                if accuracy > best["accuracy"]:
                    best = {"accuracy": accuracy, "k": k,
                            "weights": weights, "metric": metric}
                print(f"metric={metric:<9} weights={weights:<8} k={k:<2} "
                      f"validation accuracy={accuracy:.4f}")

    print(f"Selected configuration: {best}")
    _plot_hyperparameter_sweep(results)
    return best


def _plot_hyperparameter_sweep(results):
    """Plot validation accuracy against k for each metric/weighting pair."""
    plt.figure(figsize=(7, 5))
    for metric in CONFIG.METRIC_GRID:
        for weights in CONFIG.WEIGHTS_GRID:
            points = sorted((k, acc) for m, w, k, acc in results
                            if m == metric and w == weights)
            plt.plot([p[0] for p in points], [p[1] for p in points],
                     marker="o", label=f"{metric}/{weights}")
    plt.xlabel("Number of neighbours (k)")
    plt.ylabel("Validation accuracy")
    plt.title("KNN hyperparameter sweep")
    plt.legend(fontsize=8)
    plt.grid(alpha=0.3)
    plt.savefig(os.path.join(CONFIG.OUT_DIR, "knn_k_sweep.png"),
                dpi=150, bbox_inches="tight")
    plt.close()

# ---------------------------------------------------------------------------
# Evaluation
# ---------------------------------------------------------------------------
def evaluate(best, X_train, y_train, X_test, y_test):
    """Fit the selected model and report performance on the held-out test set."""
    model = KNeighborsClassifier(n_neighbors=best["k"], weights=best["weights"],
                                 metric=best["metric"], n_jobs=CONFIG.N_JOBS)

    started = time.time()
    model.fit(X_train, y_train)
    train_seconds = time.time() - started

    started = time.time()
    predictions = model.predict(X_test)
    test_seconds = time.time() - started
    probabilities = model.predict_proba(X_test)

    classes = model.classes_
    top1 = accuracy_score(y_test, predictions)
    top5 = top_k_accuracy_score(y_test, probabilities, k=5, labels=classes)
    balanced = balanced_accuracy_score(y_test, predictions)
    precision, recall, f1, _ = precision_recall_fscore_support(
        y_test, predictions, average="macro", zero_division=0)

    print("\nKNN test results")
    print(f"  configuration      k={best['k']}, weights={best['weights']}, "
          f"metric={best['metric']}, PCA={CONFIG.PCA_DIMS}")
    print(f"  top-1 accuracy     {top1:.4f}")
    print(f"  top-5 accuracy     {top5:.4f}")
    print(f"  balanced accuracy  {balanced:.4f}")
    print(f"  macro precision    {precision:.4f}")
    print(f"  macro recall       {recall:.4f}")
    print(f"  macro F1           {f1:.4f}")
    print(f"  training time      {train_seconds:.2f}s")
    print(f"  inference time     {test_seconds:.2f}s "
          f"({test_seconds / len(y_test) * 1000:.2f} ms/image)")

    matrix = confusion_matrix(y_test, predictions, labels=classes)
    plt.figure(figsize=(9, 8))
    plt.imshow(np.log1p(matrix), cmap="viridis")
    plt.title("KNN confusion matrix (log-scaled)")
    plt.xlabel("Predicted class")
    plt.ylabel("True class")
    plt.colorbar()
    plt.savefig(os.path.join(CONFIG.OUT_DIR, "knn_confusion_matrix.png"),
                dpi=150, bbox_inches="tight")
    plt.close()

    # Most frequently confused class pairs, for error analysis.
    off_diagonal = matrix.copy()
    np.fill_diagonal(off_diagonal, 0)
    pairs = sorted(
        ((off_diagonal[i, j], classes[i], classes[j])
         for i in range(len(classes)) for j in range(len(classes))
         if off_diagonal[i, j] > 0),
        reverse=True)
    print("\nMost frequently confused class pairs (true -> predicted, count)")
    for count, true_class, predicted_class in pairs[:15]:
        print(f"  {true_class} -> {predicted_class}: {count}")

    metrics = {
        "top1": top1, "top5": top5, "balanced_accuracy": balanced,
        "macro_precision": precision, "macro_recall": recall, "macro_f1": f1,
        "train_seconds": train_seconds, "test_seconds": test_seconds,
        "configuration": best, "pca_dimensions": CONFIG.PCA_DIMS,
    }
    with open(os.path.join(CONFIG.OUT_DIR, "knn_metrics.json"), "w") as handle:
        json.dump(metrics, handle, indent=2, default=str)
    with open(os.path.join(CONFIG.OUT_DIR, "knn_classification_report.txt"), "w") as handle:
        handle.write(classification_report(y_test, predictions, zero_division=0))

    return metrics

# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
def main():
    mount_drive()

    os.makedirs(CONFIG.WORK_DIR, exist_ok=True)
    os.makedirs(CONFIG.CACHE_DIR, exist_ok=True)
    os.makedirs(CONFIG.OUT_DIR, exist_ok=True)
    np.random.seed(CONFIG.RANDOM_SEED)

    train_split = load_split(CONFIG.TRAIN_CSV)
    val_split = load_split(CONFIG.VAL_CSV)
    test_split = load_split(CONFIG.TEST_CSV)

    extract_needed_images([train_split, val_split, test_split])

    X_train_raw, y_train = build_feature_matrix(train_split, "train")
    X_val_raw, y_val = build_feature_matrix(val_split, "val")
    X_test_raw, y_test = build_feature_matrix(test_split, "test")

    # Standardisation and PCA are fitted on the training split alone; the
    # validation and test splits are only transformed, preventing leakage.
    scaler = StandardScaler().fit(X_train_raw)
    pca = PCA(n_components=min(CONFIG.PCA_DIMS, X_train_raw.shape[1]),
              random_state=CONFIG.RANDOM_SEED).fit(scaler.transform(X_train_raw))

    def project(matrix):
        return pca.transform(scaler.transform(matrix))

    X_train, X_val, X_test = project(X_train_raw), project(X_val_raw), project(X_test_raw)
    print(f"PCA retained {pca.n_components_} components "
          f"({pca.explained_variance_ratio_.sum():.3f} of total variance)")

    best = tune_knn(X_train, y_train, X_val, y_val)
    evaluate(best, X_train, y_train, X_test, y_test)


if __name__ == "__main__":
    main()

!ls -la "/content/gdrive/MyDrive/COMP9517 GROUP PROJECT/knn_outputs"

!cat "/content/gdrive/MyDrive/COMP9517 GROUP PROJECT/knn_metrics.json"

!cat "/content/gdrive/MyDrive/COMP9517 GROUP PROJECT/knn_outputs/knn_metrics.json"