# -*- coding: utf-8 -*-
"""Vit Transformer Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v7FRBEaAkgq9vhHe2KI7o7ID649DQqny
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

!pip install timm

!ls "/content/drive/MyDrive/CV_Proj_Dataset"

import os
import time
import json
import tarfile

import numpy as np
import pandas as pd
from PIL import Image

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

import timm
from timm.data import resolve_data_config
from timm.data.transforms_factory import create_transform

from sklearn.metrics import (
    accuracy_score, balanced_accuracy_score, top_k_accuracy_score,
    precision_recall_fscore_support, confusion_matrix, classification_report,
)
import matplotlib
import matplotlib.pyplot as plt

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
class CONFIG:
    """Central configuration for paths, architecture and optimisation."""

    # Dataset location: label CSVs and the two source archives.
    DRIVE_ROOT = "/content/drive/MyDrive/CV_Proj_Dataset"
    # Destination for metrics, figures and checkpoints.
    RESULTS_ROOT = "/content/drive/MyDrive/COMP9517 GROUP PROJECT"
    # Local working directory holding the extracted JPEGs.
    WORK_DIR = "/content/work"

    # train/val images reside in train_mini.tar.gz; test images in val.tar.gz.
    TRAIN_TAR = "train_mini.tar.gz"
    VAL_TAR = "val.tar.gz"

    TRAIN_CSV = "train_label_500_species.csv"
    VAL_CSV = "val_label_500_species.csv"
    TEST_CSV = "test_label_500_species.csv"
    IMG_PATH_COL = "file_name"
    LABEL_COL = "category_id"

    # Architecture.
    BACKBONE = "vit_base_patch16_224"
    IMG_SIZE = 224

    # Optimisation. The randomly initialised model is trained for more epochs
    # at a higher learning rate, as it has no pretrained representation to
    # adapt and converges considerably more slowly.
    BATCH_SIZE = 32
    EPOCHS_PRETRAINED = 10
    EPOCHS_SCRATCH = 25
    LR_PRETRAINED = 3e-4
    LR_SCRATCH = 5e-4
    WEIGHT_DECAY = 0.05
    LABEL_SMOOTHING = 0.1
    NUM_WORKERS = 2
    SEED = 42

    OUT_DIR = os.path.join(RESULTS_ROOT, "vit_outputs")


os.makedirs(CONFIG.WORK_DIR, exist_ok=True)
os.makedirs(CONFIG.OUT_DIR, exist_ok=True)
torch.manual_seed(CONFIG.SEED)
np.random.seed(CONFIG.SEED)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
USE_AMP = DEVICE == "cuda"


def autocast_context():
    """Return a mixed-precision context on CUDA, or a no-op elsewhere."""
    if USE_AMP:
        return torch.cuda.amp.autocast()
    from contextlib import nullcontext
    return nullcontext()

# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------
def mount_drive():
    """Mount Google Drive when executing inside a Colab runtime."""
    try:
        from google.colab import drive
        if not os.path.exists("/content/drive/MyDrive"):
            drive.mount("/content/drive")
    except ImportError:
        pass


def _basename(path):
    """Reduce a dataset-relative path to its filename."""
    return os.path.basename(str(path).strip())


def load_split(csv_name):
    """Read a label CSV and return its image filenames and class labels."""
    df = pd.read_csv(os.path.join(CONFIG.DRIVE_ROOT, csv_name))
    columns = {c.lower(): c for c in df.columns}

    img_col = CONFIG.IMG_PATH_COL if CONFIG.IMG_PATH_COL in df.columns else next(
        (columns[c] for c in ("file_name", "filename", "image", "path", "img")
         if c in columns), None)
    label_col = CONFIG.LABEL_COL if CONFIG.LABEL_COL in df.columns else next(
        (columns[c] for c in ("category_id", "label", "class_id", "species")
         if c in columns), None)
    if img_col is None or label_col is None:
        raise ValueError(f"Could not identify image/label columns in {csv_name}.")

    split = pd.DataFrame({
        "img_full": df[img_col].astype(str),
        "img": df[img_col].map(_basename),
        "label": df[label_col],
    })
    print(f"{csv_name}: {len(split)} images, {split['label'].nunique()} classes")
    return split

# ---------------------------------------------------------------------------
# Image extraction
# ---------------------------------------------------------------------------
def _extract_from_archive(tar_path, wanted):
    """Stream a tar archive once, extracting only the requested filenames."""
    if not wanted:
        return
    if not os.path.exists(tar_path):
        print(f"Archive unavailable: {tar_path} ({len(wanted)} images skipped)")
        return

    extracted = 0
    started = time.time()
    with tarfile.open(tar_path, "r:gz") as archive:
        for member in archive:
            if not member.isfile():
                continue
            name = os.path.basename(member.name)
            if name in wanted:
                source = archive.extractfile(member)
                if source is None:
                    continue
                with open(os.path.join(CONFIG.WORK_DIR, name), "wb") as target:
                    target.write(source.read())
                extracted += 1
                wanted.discard(name)
                if not wanted:
                    break
    print(f"{os.path.basename(tar_path)}: extracted {extracted} images "
          f"in {time.time() - started:.0f}s")


def extract_needed_images(splits):
    """Extract only the images referenced by the 500-class subset."""
    present = set(os.listdir(CONFIG.WORK_DIR))
    wanted = {CONFIG.TRAIN_TAR: set(), CONFIG.VAL_TAR: set()}

    for split in splits:
        for full_path, name in zip(split["img_full"], split["img"]):
            if name in present:
                continue
            prefix = str(full_path).split("/", 1)[0]
            archive = CONFIG.VAL_TAR if prefix == "val" else CONFIG.TRAIN_TAR
            wanted[archive].add(name)

    if not any(wanted.values()):
        print("All required images are already available.")
        return

    for archive, names in wanted.items():
        _extract_from_archive(os.path.join(CONFIG.DRIVE_ROOT, archive), names)

# ---------------------------------------------------------------------------
# Dataset and loaders
# ---------------------------------------------------------------------------
class SpeciesDataset(Dataset):
    """Image dataset backed by a label CSV and a directory of JPEGs."""

    def __init__(self, split, label_to_index, transform):
        paths = [os.path.join(CONFIG.WORK_DIR, name) for name in split["img"]]
        labels = [label_to_index[label] for label in split["label"]]

        available = [i for i, path in enumerate(paths) if os.path.exists(path)]
        self.paths = [paths[i] for i in available]
        self.labels = [labels[i] for i in available]
        self.transform = transform

    def __len__(self):
        return len(self.paths)

    def __getitem__(self, index):
        image = Image.open(self.paths[index]).convert("RGB")
        return self.transform(image), self.labels[index]


def build_loaders(train_split, val_split, test_split, label_to_index):
    """Construct the training, validation and test data loaders.

    Normalisation statistics are taken from the backbone's own configuration.
    RandAugment is applied to the training split only; validation and test use
    deterministic resize-and-centre-crop transforms.
    """
    data_config = resolve_data_config(
        {}, model=timm.create_model(CONFIG.BACKBONE, pretrained=False))

    train_transform = create_transform(
        input_size=CONFIG.IMG_SIZE, is_training=True,
        mean=data_config["mean"], std=data_config["std"],
        auto_augment="rand-m7-mstd0.5")
    eval_transform = create_transform(
        input_size=CONFIG.IMG_SIZE, is_training=False,
        mean=data_config["mean"], std=data_config["std"])

    def loader(dataset, shuffle):
        return DataLoader(dataset, batch_size=CONFIG.BATCH_SIZE, shuffle=shuffle,
                          num_workers=CONFIG.NUM_WORKERS, pin_memory=True,
                          drop_last=shuffle)

    return (
        loader(SpeciesDataset(train_split, label_to_index, train_transform), True),
        loader(SpeciesDataset(val_split, label_to_index, eval_transform), False),
        loader(SpeciesDataset(test_split, label_to_index, eval_transform), False),
    )

# ---------------------------------------------------------------------------
# Training and inference
# ---------------------------------------------------------------------------
@torch.no_grad()
def predict(model, loader, return_probabilities=False):
    """Run inference over a loader and return labels, predictions and scores."""
    model.eval()
    all_labels, all_predictions, all_probabilities = [], [], []

    for images, labels in loader:
        images = images.to(DEVICE, non_blocking=True)
        with autocast_context():
            logits = model(images)
        probabilities = torch.softmax(logits.float(), dim=1).cpu().numpy()
        all_predictions.append(probabilities.argmax(1))
        all_labels.append(labels.numpy())
        if return_probabilities:
            all_probabilities.append(probabilities)

    y_true = np.concatenate(all_labels)
    y_pred = np.concatenate(all_predictions)
    probabilities = np.concatenate(all_probabilities) if return_probabilities else None
    return accuracy_score(y_true, y_pred), y_true, y_pred, probabilities


def train_model(mode, train_loader, val_loader, num_classes):
    """Train ViT-B/16 in either the 'pretrained' or 'scratch' setting.

    The parameters achieving the highest validation accuracy are retained, so
    that the reported test performance corresponds to the selected checkpoint
    rather than the final epoch.
    """
    pretrained = mode == "pretrained"
    epochs = CONFIG.EPOCHS_PRETRAINED if pretrained else CONFIG.EPOCHS_SCRATCH
    learning_rate = CONFIG.LR_PRETRAINED if pretrained else CONFIG.LR_SCRATCH

    print(f"\nTraining ViT-B/16 [{mode}]: {epochs} epochs, "
          f"learning rate {learning_rate}, device {DEVICE}")

    model = timm.create_model(CONFIG.BACKBONE, pretrained=pretrained,
                              num_classes=num_classes).to(DEVICE)
    optimiser = torch.optim.AdamW(model.parameters(), lr=learning_rate,
                                  weight_decay=CONFIG.WEIGHT_DECAY)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimiser, T_max=epochs)
    criterion = nn.CrossEntropyLoss(label_smoothing=CONFIG.LABEL_SMOOTHING)
    scaler = torch.cuda.amp.GradScaler(enabled=USE_AMP)

    history = {"train_loss": [], "val_accuracy": []}
    best_accuracy, best_state = -1.0, None
    started = time.time()

    for epoch in range(1, epochs + 1):
        model.train()
        running_loss, seen = 0.0, 0

        for images, labels in train_loader:
            images = images.to(DEVICE, non_blocking=True)
            labels = labels.to(DEVICE, non_blocking=True)
            optimiser.zero_grad(set_to_none=True)

            if USE_AMP:
                with autocast_context():
                    loss = criterion(model(images), labels)
                scaler.scale(loss).backward()
                scaler.step(optimiser)
                scaler.update()
            else:
                loss = criterion(model(images), labels)
                loss.backward()
                optimiser.step()

            running_loss += loss.item() * images.size(0)
            seen += images.size(0)

        scheduler.step()
        train_loss = running_loss / max(seen, 1)
        val_accuracy = predict(model, val_loader)[0]
        history["train_loss"].append(train_loss)
        history["val_accuracy"].append(val_accuracy)
        print(f"  epoch {epoch:>2}  train loss {train_loss:.3f}  "
              f"validation top-1 {val_accuracy:.4f}")

        if val_accuracy > best_accuracy:
            best_accuracy = val_accuracy
            best_state = {k: v.detach().cpu().clone()
                          for k, v in model.state_dict().items()}

    train_seconds = time.time() - started
    if best_state is not None:
        model.load_state_dict(best_state)
    print(f"  best validation top-1 {best_accuracy:.4f} "
          f"({train_seconds:.0f}s total)")

    return model, history, train_seconds

# ---------------------------------------------------------------------------
# Evaluation
# ---------------------------------------------------------------------------
def evaluate(mode, model, test_loader, num_classes, train_seconds, history):
    """Report test performance and write metrics and figures to disk."""
    started = time.time()
    top1, y_true, y_pred, probabilities = predict(model, test_loader,
                                                  return_probabilities=True)
    test_seconds = time.time() - started

    labels = np.arange(num_classes)
    top5 = top_k_accuracy_score(y_true, probabilities, k=5, labels=labels)
    balanced = balanced_accuracy_score(y_true, y_pred)
    precision, recall, f1, _ = precision_recall_fscore_support(
        y_true, y_pred, average="macro", zero_division=0)

    print(f"\nViT-B/16 [{mode}] test results")
    print(f"  top-1 accuracy     {top1:.4f}")
    print(f"  top-5 accuracy     {top5:.4f}")
    print(f"  balanced accuracy  {balanced:.4f}")
    print(f"  macro precision    {precision:.4f}")
    print(f"  macro recall       {recall:.4f}")
    print(f"  macro F1           {f1:.4f}")
    print(f"  training time      {train_seconds:.0f}s")
    print(f"  inference time     {test_seconds:.1f}s "
          f"({test_seconds / len(y_true) * 1000:.2f} ms/image)")

    tag = f"vit_{mode}"

    matrix = confusion_matrix(y_true, y_pred, labels=labels)
    plt.figure(figsize=(9, 8))
    plt.imshow(np.log1p(matrix), cmap="viridis")
    plt.title(f"ViT-B/16 [{mode}] confusion matrix (log-scaled)")
    plt.xlabel("Predicted class")
    plt.ylabel("True class")
    plt.colorbar()
    plt.savefig(os.path.join(CONFIG.OUT_DIR, f"{tag}_confusion.png"),
                dpi=150, bbox_inches="tight")
    plt.close()

    epochs = range(1, len(history["train_loss"]) + 1)
    figure, loss_axis = plt.subplots(figsize=(7, 5))
    loss_axis.plot(epochs, history["train_loss"], "b-o")
    loss_axis.set_xlabel("Epoch")
    loss_axis.set_ylabel("Training loss", color="b")
    accuracy_axis = loss_axis.twinx()
    accuracy_axis.plot(epochs, history["val_accuracy"], "r-s")
    accuracy_axis.set_ylabel("Validation top-1 accuracy", color="r")
    plt.title(f"ViT-B/16 [{mode}] training dynamics")
    plt.savefig(os.path.join(CONFIG.OUT_DIR, f"{tag}_curves.png"),
                dpi=150, bbox_inches="tight")
    plt.close()

    metrics = {
        "mode": mode, "top1": top1, "top5": top5, "balanced_accuracy": balanced,
        "macro_precision": precision, "macro_recall": recall, "macro_f1": f1,
        "train_seconds": train_seconds, "test_seconds": test_seconds,
        "epochs": len(history["train_loss"]), "backbone": CONFIG.BACKBONE,
    }
    with open(os.path.join(CONFIG.OUT_DIR, f"{tag}_metrics.json"), "w") as handle:
        json.dump(metrics, handle, indent=2, default=str)
    with open(os.path.join(CONFIG.OUT_DIR, f"{tag}_report.txt"), "w") as handle:
        handle.write(classification_report(y_true, y_pred, zero_division=0))
    torch.save(model.state_dict(), os.path.join(CONFIG.OUT_DIR, f"{tag}_weights.pt"))

    return metrics

# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
def main():
    print(f"Device: {DEVICE}")
    mount_drive()

    train_split = load_split(CONFIG.TRAIN_CSV)
    val_split = load_split(CONFIG.VAL_CSV)
    test_split = load_split(CONFIG.TEST_CSV)

    extract_needed_images([train_split, val_split, test_split])

    # Map the dataset's category identifiers onto a contiguous index range, as
    # required by the cross-entropy objective.
    classes = sorted(train_split["label"].unique())
    label_to_index = {label: index for index, label in enumerate(classes)}
    num_classes = len(classes)
    with open(os.path.join(CONFIG.OUT_DIR, "vit_label_map.json"), "w") as handle:
        json.dump({str(k): v for k, v in label_to_index.items()}, handle)
    print(f"{num_classes} classes")

    train_loader, val_loader, test_loader = build_loaders(
        train_split, val_split, test_split, label_to_index)

    results = {}
    for mode in ("pretrained", "scratch"):
        model, history, train_seconds = train_model(
            mode, train_loader, val_loader, num_classes)
        results[mode] = evaluate(mode, model, test_loader, num_classes,
                                 train_seconds, history)

    print("\nSummary")
    for mode, metrics in results.items():
        print(f"  {mode:<11} top-1 {metrics['top1']:.4f}  "
              f"top-5 {metrics['top5']:.4f}  macro F1 {metrics['macro_f1']:.4f}")


if __name__ == "__main__":
    main()